### ISSUE TITLE
test suite issue on 32-bit archs: cannot use MaxIPv4 (untyped int constant 4294967295) as int value in argument to t.Errorf (overflows)

### ISSUE THREAD

**Issue by CyrilBrulebois** [c-robinson/iplib#11]
Hi,

I'm packaging your software for Debian (as a build-dependency for https://www.crowdsec.net/) and I'm seeing the following test failure on 32-bit archs (e.g. armel, armhf, i386 as seen on https://ci.debian.net/packages/g/golang-github-c-robinson-iplib/):

```
   dh_auto_test -O--builddirectory=_build -O--buildsystem=golang
	cd _build && go test -vet=off -v -p 32 github.com/c-robinson/iplib github.com/c-robinson/iplib/iana github.com/c-robinson/iplib/iid
# github.com/c-robinson/iplib [github.com/c-robinson/iplib.test]
src/github.com/c-robinson/iplib/iplib_test.go:362:30: cannot use MaxIPv4 (untyped int constant 4294967295) as int value in argument to t.Errorf (overflows)
FAIL	github.com/c-robinson/iplib [build failed]
```

It can be trivially reproduced in an i386 chroot on an amd64 machine.

Casting the constant explicitly to `uint` in that error message does the trick, but maybe it should or could have been declared a `uint32` in the first place? That being said, I don't know anything about Go, so I'll just mention the patch I'm considering applying to `iplib_test.go` in the Debian package until I've gotten some feedback here:

```diff
-               t.Errorf("want %d got %d", MaxIPv4, i)
+               t.Errorf("want %d got %d", uint(MaxIPv4), i)
```

**Comment by c-robinson** [comment]
thanks for the issue and the solution!
