### ISSUE TITLE
Incorrect Example Using iplib.Net4

### ISSUE THREAD

**Issue by ikandars** [c-robinson/iplib#7]
Hi,

I found incorrect dos in readme file related to using iplib.Net4. In this line:

> n := NewNet4(net.ParseIP("192.168.0.0"), 16)

it should be:

> n := iplib.NewNet4(net.ParseIP("192.168.0.0"), 16)

and in this one:

> fmt.Println(n.Network())          // 192.168.0.0

it should be:

> fmt.Println(n.IP())          // 192.168.0.0

**Comment by c-robinson** [comment]
Thanks for noticing these, they'll be corrected in 1.0.3
