### ISSUE TITLE
Integer overflow on 32bit targets

### ISSUE THREAD

**Issue by 0xd61** [c-robinson/iplib#8]
This line causes an integer overflow when compiling for arm.

https://github.com/c-robinson/iplib/blob/d4ce4cb249581363ae573157898db9f904c971fa/net6.go#L337

The solution would be to use uint32 instead of int for the datatype.

The error message is:
`vendor/github.com/c-robinson/iplib/net6.go:337:21: constant 4294967295 overflows int`

**Comment by c-robinson** [comment]
Thank you kindly for the fix!
